// This file is automatically generated. Keep Desktop-specific behavior in the
// Vite alias; this module only exposes the same public contract so shared
// components can compile in both Web and Desktop builds.
import { createClient } from '@supabase/supabase-js';
import type { Session } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect the configured cloud backend.`;
    console.error(`[Database] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

/**
 * Shared recovery contract. The Desktop build aliases this module to the native
 * implementation, which additionally heals synthetic/offline device sessions.
 * On the Web this simply validates the persisted session and refreshes it when
 * near expiry, keeping DesktopRealtimeSync safe to include in the shared tree.
 */
export async function recoverDesktopCloudSession(): Promise<Session | null> {
  if (typeof navigator !== 'undefined' && navigator.onLine === false) return null;
  const { data } = await supabase.auth.getSession();
  let session = data.session;
  if (!session) return null;

  const expiresAtMs = session.expires_at ? session.expires_at * 1000 : Number.POSITIVE_INFINITY;
  if (expiresAtMs <= Date.now() + 60_000) {
    try {
      const refreshed = await supabase.auth.refreshSession();
      if (refreshed.data.session) session = refreshed.data.session;
    } catch {
      // A still-valid persisted token can continue until the normal auth layer
      // reports a real authentication error.
    }
  }

  return session;
}
